PyConversion/urls.py
from django.contrib import admin
from django.urls import path , include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions



urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('apis.urls')),
    path('',include('accounts.urls')),
    path('currency/',include('currency.urls')),
    path('videocon/',include('videocon.urls')),
    path('document/',include('docum.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    
]

from django.conf.urls.static import static
from PyConversion import settings
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

schema_view = get_schema_view(
    openapi.Info(
        title="PyConversion BACKEND API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
 
)


urlpatterns += [
    path(
        "swagger(?P<format>\.json|\.yaml)",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

apis/urls.py
from django.urls import path
from apis.document_api.api import DocumentConvertView ,DocumentConvertGetData 
from apis.currency_api.api import CurrencyConvertView ,CurrencyConvertGetData
from apis.videocon_api.api import VideoConvertView ,VideoConvertGetData

urlpatterns = [
    path('currencypostdata/', CurrencyConvertView.as_view()),
    path('currencygetdata/<int:id>/',CurrencyConvertGetData.as_view()),
    path('documentpostdata/', DocumentConvertView.as_view()),
    path('documentgetdata/<int:id>/',DocumentConvertGetData.as_view()),
    path('videopostdata/',VideoConvertView.as_view()),
    path('videogetdata/<int:id>/',VideoConvertGetData.as_view()),
]

docum/urls.py
from django.contrib import admin
from django.urls import path
from docum import views

app_name="docum"

urlpatterns = [
    path('docversion/',views.docx2pdf_converter, name = 'docversion'),
    # path('rom/<uuid:task_id>',views.get_progress , name = 'task_status'),
    path('download/<int:id>/',views.downloadfile , name = 'download'),
]

videocon/urls.py
from django.contrib import admin
from django.urls import path 
from videocon import views

urlpatterns = [
    path('video/', views.index , name = 'videocon'),
    path('download1/<int:id>/',views.downloadfile , name = 'download1'),

]

accounts/models.py
from django.db import models



class UserContactDetails(models.Model):
  first_name = models.CharField(max_length = 100)
  last_name = models.CharField(max_length = 100)
  user_email = models.EmailField()
  contact_number = models.CharField(max_length = 10)
  
  def __str__(self):
    return self.first_name


class UserRegisterModel(models.Model):
    full_name = models.CharField(max_length=255)
    your_email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    confirm_password = models.CharField(max_length=255)

    def __str__(self):
        return self.full_name

apis/models.py
from django.db import models

CONVERT_CHOICES = (
    ("US Dollar", "USD"),
    ("Euro", "EURO"),
    ("British Pound","ASTRLN"),
    ("Australian Dollar","BRTSH"),
    ("Canadian Dollar", "CNDN"),
    ("Singapore Dollar", "SNGPR"),
    ("Swiss Franc", "SWSFRNC"),
    ("Malaysian Ringgit","MLYSN"),
    ("Japanese Yen","JPNS"),
    ("Chinese Yuan Renminbi","CHNS"),
    ("Indian Rupee","INR"),
) 


class Currency_convert(models.Model):
    current_choice = models.CharField(max_length = 50 , choices= CONVERT_CHOICES)
    amount = models.IntegerField()
    convert_choice = models.CharField(max_length = 50 , choices= CONVERT_CHOICES)
    result = models.IntegerField(null=True)
    
    


CONVERT_CHOICES = (
    ("pdf", "PDF"),
    ("docx", "DOCX"),
    ("html", "HTML"),
)

class UserFileUpload(models.Model):
   current_choices = models.CharField(max_length = 20,choices = CONVERT_CHOICES)
   file = models.FileField() 
   convert_choices = models.CharField(max_length = 20,choices = CONVERT_CHOICES)
   
   

VIDEO_CHOICES = (
    
    ("GIF","GIF"),
    ("AUDIO","AUDIO"),
    ("Image","Image"),
    
) 

class VideoConvertModel(models.Model):
    video   = models.FileField(upload_to="video/%y")
    VIDEO_CHOICES = models.CharField(max_length=100 ,choices=VIDEO_CHOICES)
    

videocon/models.py
from django.db import models

# Create your models here.
VIDEO_CHOICES = (
    
    ("GIF","GIF"),
    ("AUDIO","AUDIO"),
    ("Image","Image"),
    
) 

class Video(models.Model):
    video   = models.FileField()
    VIDEO_CHOICES = models.CharField(max_length=100 ,choices=VIDEO_CHOICES)
    converted_video = models.FileField(null=True,blank=True) 

videocon/forms.py
from django import forms
from .models import Video

class Video_form(forms.ModelForm):
  class Meta:
    model = Video
    fields = '__all__'

videocon/views.py
import re
from django.shortcuts import redirect, render
from videocon.models import Video
from django.http import HttpResponse, HttpResponseRedirect
from videocon.forms import Video_form
import os
import time
from videocon.tasks import VideoFunction
# Create your views here.

# Code of  convert mp4 to Gif ------------------->>     
def index(request):
    if request.method =='POST':
        form = Video_form(request.POST, request.FILES)
        if form.is_valid():
            form_file_data = form.cleaned_data['video']
            form_choice_data = form.cleaned_data['VIDEO_CHOICES']
            form_file_data = str(form_file_data)
            form_choice_data = str(form_choice_data)
            fm=form.save()
            instance_id =fm.id
            result = VideoFunction.delay(form_file_data,form_choice_data,instance_id)
            print(result)
            while result.status != 'SUCCESS':
                time.sleep(3)
            return redirect(f'/videocon/download1/{instance_id}')
    else:
        form = Video_form()
    return render(request,"videocon.html",{'form':form})


def downloadfile(request,id):
    userfiledownload = Video.objects.get(id=id)
    return render(request,'download1.html',{'download1':userfiledownload})

templates/aboutus.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<!-- About Start -->
<div class="container-xxl py-6">
  <div class="container">
      <div class="row g-5 align-items-center">
          <div class="col-lg-6 wow zoomIn" data-wow-delay="0.1s">
              <img src="{% static "images/image1.jpg" %}" class="img-fluid" alt="My image"/>
          </div>
          <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">
              <h2 class="mb-4">Award Wining Consultancy Agency For Your Business</h2>
              <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod</p>
              <div class="row g-3 mb-4">
                  <div class="col-12 d-flex">
                      <div class="flex-shrink-0 btn-lg-square rounded-circle bg-primary">
                          <i class="fa fa-user-tie text-white"></i>
                      </div>
                      <div class="ms-4">
                          <h6>Business Planning</h6>
                          <span>Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem sit clita duo</span>
                      </div>
                  </div>
                  <div class="col-12 d-flex">
                      <div class="flex-shrink-0 btn-lg-square rounded-circle bg-primary">
                          <i class="fa fa-chart-line text-white"></i>
                      </div>
                      <div class="ms-4">
                          <h6>Financial Analaysis</h6>
                          <span>Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem sit clita duo</span>
                      </div>
                  </div>
              </div>
              <a class="btn btn-primary rounded-pill py-3 px-5 mt-2" href="">Read More</a>
          </div>
      </div>
  </div>
</div>
<!-- About End -->
{% endblock content %}
</body>
</html>

templates/base.html
    <html lang="en">
    {% load static %}
    <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Currency/Document/Coversion</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin=" anonymous ">
    </script>

    
    <link rel="stylesheet"type="text/css" href="{% static 'css/style.css' %}"/>

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <style>
    body  {
        background-color: #395b99;
        background-repeat: no-repeat;
        background-attachment: fixed;
        }
        .description {
            left: 50%;
            position: absolute;
            top: 230%;
            transform: translate(-50%, -55%);
            text-align: center;
            }
        .description h1 {
            color: hsl(100, 58%, 55%);
        }
        .description p {
            color: rgb(8, 9, 43);
            font-size: 1.3rem;
            line-height: 1.5;
        }
        .mySlides {display:none;}
        #band
        {
            background-color: white;
            position: relative;
            max-width: 1440px;
            
        }
    </style>
    </head>
    <body>
    <div class="container-xxl bg-white p-0">
    <div class="container-xxl position-relative p-0">
        <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
            <a href="index.html" class="navbar-brand p-0">
                <h1 class="m-0">PyConversion</h1>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'home' %}" class="nav-item nav-link ">Home</a>
                <a href="{% url 'aboutus' %}" class="nav-item nav-link">About</a>
                <a href="{% url 'create' %}" class="nav-item nav-link">Contact</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Conversion</a>
                        <div class="dropdown-menu m-0">
                            <a href="{% url 'currency' %}" class="dropdown-item">Currency Conversion</a>
                            <a href="{% url 'docum:docversion' %}" class="dropdown-item">Document Conversion</a>
                            <a href="{% url 'videocon' %}"  class="dropdown-item">Video conversion</a>
                        </div>
                </div>
            </div>
                <a href="" class="btn btn-light rounded-pill text-primary py-2 px-4 ms-lg-5">Login</a>
            </div>
        </nav>
    </div>
    </div>
    
    {% block content %}
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <div class = "slider-w3">
    <div class="w3-content w3-display-container">
        <img class="mySlides" src="{% static "images/image2.jpg" %}" style="width:140% ;position: relative; right:20%;height:100vh">
        <img class="mySlides" src="{% static "images/image3.jpg" %}" style="width:140% ;position: relative; right:20%;height:100vh">
        <img class="mySlides" src="{% static "images/image4.jpeg" %}" style="width:140% ;position: relative; right:20%;height:100vh">
      
        <button class="w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="w3-display-right" onclick="plusDivs(1)">&#10095;</button>
      </div>
    </div>
    <!-- The Band Section -->
  <div class="w3-container w3-content w3-center w3-padding-64" id="band">
    <h2 class="w3-wide">Conversion</h2>
    <p class="w3-justify">
        A conversion rate is the ratio between two currencies,
        most commonly used in foreign exchange markets, which designates how much 
        of one currency is needed to exchange for the equivalent value of 
        another currency. Conversion rates fluctuate regularly for all currencies 
        traded in forex markets. Forex spot prices are quoted continuously 
        with one day's break over weekends.</p>
    <div class="w3-row w3-padding-32">
      <div class="w3-third">
        <p>Video Conversion</p>
        <img src="{% static "images/image5.png" %}" class="w3-round w3-margin-bottom" alt="Random Name" style="width:90%;height:50vh">
      </div>
      <div class="w3-third">
        <p>Currency Conversion</p>
        <img src="{% static "images/image6.jpg" %}" class="w3-round w3-margin-bottom" alt="Random Name" style="width:90%;height:50vh">
      </div>
      <div class="w3-third">
        <p>Document Conversion</p>
        <img src="{% static "images/image7.jpeg" %}" class="w3-round" alt="Random Name" style="width:90%;height:50vh">
      </div>
    </div>
  </div>
  <footer class="w3-center w3-black w3-padding-64">
    <div class="w3-xlarge w3-section">
      <i class="fa fa-facebook-official w3-hover-opacity"></i>
      <i class="fa fa-instagram w3-hover-opacity"></i>
      <i class="fa fa-snapchat w3-hover-opacity"></i>
      <i class="fa fa-pinterest-p w3-hover-opacity"></i>
      <i class="fa fa-twitter w3-hover-opacity"></i>
      <i class="fa fa-linkedin w3-hover-opacity"></i>
    </div>
    <p>Powered by <a href="/" target="_blank" class="w3-hover-text-green">PyConversion</a></p>
  </footer>
      <script>
        var slideIndex = 1;
        showDivs(slideIndex);
        
        function plusDivs(n) {
          showDivs(slideIndex += n);
        }
        
        function showDivs(n) {
          var i;
          var x = document.getElementsByClassName("mySlides");
          if (n > x.length) {slideIndex = 1}
          if (n < 1) {slideIndex = x.length}
          for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";  
          }
          x[slideIndex-1].style.display = "block";  
        }
        </script>
    {% endblock content %}
    </body>
    </html>

templates/createview.html
{% extends 'base.html' %}
{% block content %}
<style>
.contact-form-wrapper {
  margin-top: 0px;
}
.contact-form {
  margin-top:120px;
  padding: 60px 40px;
  background-color: #ffffff;
  border-radius: 17px;
  max-width: 600px;
}

.contact-form textarea {
  resize: none;
}

.contact-form .form-input,
.form-text-area {
  background-color: #f0f4f5;
  height: 40px;
  padding-left: 26px;
}

.contact-form .form-text-area {
  background-color: #f0f4f5;
  height: auto;
  padding-left: 16px;
}

.contact-form .form-control::placeholder {
  color: #aeb4b9;
  font-weight: 500;
  opacity: 1;
}

.contact-form .form-control:-ms-input-placeholder {
  color: #aeb4b9;
  font-weight: 500;
}

.contact-form .form-control::-ms-input-placeholder {
  color: #aeb4b9;
  font-weight: 500;
}

.contact-form .form-control:focus {
  border-color: #04803c;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.07), 0 0 8px #047e3b;
}

.contact-form .title {
  text-align: center;
  font-size: 24px;
  font-weight: 500;
}

.contact-form .description {
  color: #aeb4b9;
  font-size: 14px;
  text-align: center;
}

.contact-form .submit-button-wrapper {
  text-align: center;
}

.contact-form .submit-button-wrapper input {
  border: none;
  border-radius: 4px;
  background-color: #3d9259;
  color: white;
  text-transform: uppercase;
  padding: 10px 60px;
  font-weight: 500;
  letter-spacing: 2px;
}

.contact-form .submit-button-wrapper input:hover {
  background-color: #00d30b;
}
</style>
<div>
  <div class="contact-form-wrapper d-flex justify-content-center">
		<form action="" method="post" class="contact-form" novalidate>
			{% csrf_token %}
      <h5 class="title">Contact us</h5>
      <div>
				<input type="text" name="first_name" maxlength="100" class="form-control rounded border-white mb-3 form-input" id="name" placeholder="Name"required id="id_first_name">
      </div>
      <div>
				<input type="text" name="last_name" maxlength="100" class="form-control rounded border-white mb-3 form-input" placeholder="Last Name" required required id="id_last_name">
      </div>
      <div>
				<input type="email" name="user_email" maxlength="254" class="form-control rounded border-white mb-3 form-input" placeholder="Email" required required id="id_user_email">
      </div>
      <div>
				<input type="text" name="contact_number" maxlength="10" class="form-control rounded border-white mb-3 form-input" placeholder="Contact" required id="id_contact_number">
      </div>
      <div class="submit-button-wrapper">
        <input type="submit" value="Send">
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/currversion.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<center>
<div class="container-xxl py-6">
  <div class="container">
      <div class="row g-5 align-items-center">
				<h4 class="text-dark alert alert-secondary">Currency Converter</h4>
				<form action="" type=file enctype="multipart/form-data" method="post" style="position: relative; top:10px">
					{% csrf_token %}
					{{ form.as_table}}
					<br><br><br>
					<input type="submit" class=" btn btn-primary" value="Convert">
					</form>
				<br><br><br><br>
				<button type="button"class=" btn btn-default" style="width:300px; margin-left:450px; margin-top:22px;" >{{key}}</button>
			</div>
      </div>
  </div>
</div>
</center>
{% endblock content %}

templates/docversion.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
	<style>
		#progress-bar {
			margin-top: 1em;
		}
		
	</style>
<script src="{% static 'js/celery_progress.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
		jQuery(document).ready(function($)
		{
			$("#id_current_choices").click(function()
			{
				var value=$(this).val()
				if (value == "pdf")
				{
					$('#id_file').attr("accept", "." + $(this).val())
				}
				else if (value == "docx")
				{
					$('#id_file').attr("accept", "." + $(this).val())
				}
				else (value == "html")
				{
					$('#id_file').attr("accept", "." + $(this).val())
				}
			});
		});
	</script>

	<div class="container-xxl py-6">
		<div class="container">
				<div>
					<div class="row">
						<div class="col-sm-12">
							<center>	<h4 class="text-dark alert alert-secondary">Document Converter</h4></center>
							<br>
							<div class="col-sm-12">
								<center>	
									<form action="" id="login_form" type=file  enctype="multipart/form-data" method="post" style="position: relative; top:20px;">
									{% csrf_token %}
								<div class="row">
									<div class="col-sm-4">
										<b><label for="id_current_choices">Current choices:</label></b> - <select name="current_choices" required id="id_current_choices">
											<option value="" selected>---------</option>
											<option value="pdf">PDF</option>
											<option value="docx">DOCX</option>
											<option value="html">HTML</option>
											</select>
									</div>
									<div class="col-sm-4">
										<b><label for="id_file">File:</label></b> - <input type="file"  accept="" name="file" required id="id_file"> 
									</div>
									<div class="col-sm-4">
										<b><label for="id_convert_choices">Convert choices:</label></b> - <select name="convert_choices" required id="id_convert_choices">
											<option value="" selected>---------</option>  
											<option value="pdf">PDF</option>
											<option value="docx">DOCX</option>
											<option value="html">HTML</option>
										</select> 
									</div>
									</div>  
								</div>
								<br><br>
								<center>
									<input type="submit" class="btn btn-primary" value="Convert">
								</center>
							</form>
						</div>
						</div>
					</div>  
				</div>
				</div>
		</div>
	</div>
	</center>
	{% endblock content %}

templates/download.html
{% extends 'base.html' %}
{% block content %}
<style>
  @import url('https://fonts.googleapis.com/css?family=Teko|Yanone+Kaffeesatz');

#body {
  display: flex;
  flex-flow: column wrap;
  align-items: center;
  position: relative;
  top: 200px;
}
h1, h3 {
  font-family: Teko;
  margin-bottom: 0;
}
#wrapper {
  display: flex;
  flex-flow: row wrap;
}
.inner-wrapper {
  text-align: center;
  margin-right: 10px;
}
.cta, .cta-2 {
  font-family: Yanone Kaffeesatz;
  display: inline-block;
  cursor: pointer;
  color: white;
  padding: 15px 10px;
  background-color: black;
  border: 2px solid black;
  text-transform: uppercase;
}
.cta a, .cta-2 a {
  color: white;
  text-decoration: none;
}
.cta:hover, .cta-2:hover {
  background-color: white;
} 
.cta:hover a, .cta-2:hover {
  color: black;
  text-decoration: none;
}
</style>
<center>
  <div id="body">
    <h1>Button To Click Converted File  </h1>
    <h2> Time left: <span id="count"></span></h2>
    <div id="wrapper">
      <div class="inner-wrapper">
        <div class="ct">
          <a href="#"  class="btn btn-success"   id="btnCounter"
          aria-disabled="true">
           Download
        </a>
        </div>
      </div>
      </div>
    </div>
  </div>
</center>
<script>
var spn = document.getElementById("count");
var btn = document.getElementById("btnCounter");
var reloaded =true;
var count = 5;     
var timer = null; 

(function countDown()
{
  spn.textContent = count;
  if(count !== 0)
  {
    timer = setTimeout(countDown, 1000);
    count--; 
  } 
  else 
  {
    var a = document.getElementById('btnCounter');
    {% if download.converted_file %}
    a.href = "{{download.converted_file.url}}";
    a.removeAttribute("aria-disabled");
    {% endif %}
  }
}());
</script>
{% endblock content %}

templates/download1.html
{% extends 'base.html' %}
{% block content %}
<style>
  @import url('https://fonts.googleapis.com/css?family=Teko|Yanone+Kaffeesatz');

#body {
  display: flex;
  flex-flow: column wrap;
  align-items: center;
  position: relative;
  top: 200px;
}
h1, h3 {
  font-family: Teko;
  margin-bottom: 0;
}
#wrapper {
  display: flex;
  flex-flow: row wrap;
}
.inner-wrapper {
  text-align: center;
  margin-right: 10px;
}
.cta, .cta-2 {
  font-family: Yanone Kaffeesatz;
  display: inline-block;
  cursor: pointer;
  color: white;
  padding: 15px 10px;
  background-color: black;
  border: 2px solid black;
  text-transform: uppercase;
}
.cta a, .cta-2 a {
  color: white;
  text-decoration: none;
}
.cta:hover, .cta-2:hover {
  background-color: white;
} 
.cta:hover a, .cta-2:hover {
  color: black;
  text-decoration: none;
}
</style>
<center>
  <div id="body">
    <h1>Button To Click Converted File  </h1>
    <h2> Time left: <span id="count"></span></h2>
    <div id="wrapper">
      <div class="inner-wrapper">
        <div class="ct">
          <a href="#"  class="btn btn-success"   id="btnCounter"
          aria-disabled="true">
           Download
        </a>
        </div>
      </div>
      </div>
    </div>
  </div>
</center>
<script>
var spn = document.getElementById("count");
var btn = document.getElementById("btnCounter");
var reloaded =true;
var count = 5;     
var timer = null; 

(function countDown()
{
  spn.textContent = count;
  if(count !== 0)
  {
    timer = setTimeout(countDown, 1000);
    count--; 
  } 
  else 
  {
    var a = document.getElementById('btnCounter');
    {% if download1.converted_video %}
    a.href = "{{download1.converted_video.url}}";
    a.removeAttribute("aria-disabled");
    {% endif %}
  }
}());
</script>
{% endblock content %}

templates/videocon.html
{% extends 'base.html' %}
{% block content %}
<center>
<div class="container-xxl py-6">
  <div class="container">
      <div class="row g-5 align-items-center">
				<h4 class="text-dark alert alert-secondary">Video Converter</h4>
				<br><br>
				<form action="" enctype="multipart/form-data" method="post" style="position: relative; top:20px;">
					{% csrf_token %}
					<tr>
						<th><label for="id_video">Video:</label></th>
						<td>
							<input type="file" name="video" required id="id_video" accept="video/*">
						</td>
					</tr>
					<tr>
						<th><label for="id_VIDEO_CHOICES">VIDEO CHOICES:</label></th>
						<td>
							<select name="VIDEO_CHOICES" required id="id_VIDEO_CHOICES">
								<option value="" selected>Select Option</option>
								<option value="GIF">GIF</option>
								<option value="AUDIO">AUDIO</option>
								<option value="Image">Image</option>
							</select>
						</td>
					</tr>
					<br><br><br>
					<input type="submit" class=" btn btn-primary" value="Convert">
				</form>
				<br>
			</div>
      </div>
</div>
</center>
{% endblock content %}